md test01
copy 01. test01\Garden.INP
copy 01.a test01\Garden.OUT
md test02
copy 02. test02\Garden.INP
copy 02.a test02\Garden.OUT
md test03
copy 03. test03\Garden.INP
copy 03.a test03\Garden.OUT
md test04
copy 04. test04\Garden.INP
copy 04.a test04\Garden.OUT
md test05
copy 05. test05\Garden.INP
copy 05.a test05\Garden.OUT
md test06
copy 06. test06\Garden.INP
copy 06.a test06\Garden.OUT
md test07
copy 07. test07\Garden.INP
copy 07.a test07\Garden.OUT
md test08
copy 08. test08\Garden.INP
copy 08.a test08\Garden.OUT
md test09
copy 09. test09\Garden.INP
copy 09.a test09\Garden.OUT
md test10
copy 10. test10\Garden.INP
copy 10.a test10\Garden.OUT
md test11
copy 11. test11\Garden.INP
copy 11.a test11\Garden.OUT
md test12
copy 12. test12\Garden.INP
copy 12.a test12\Garden.OUT
md test13
copy 13. test13\Garden.INP
copy 13.a test13\Garden.OUT
md test14
copy 14. test14\Garden.INP
copy 14.a test14\Garden.OUT
md test15
copy 15. test15\Garden.INP
copy 15.a test15\Garden.OUT
md test16
copy 16. test16\Garden.INP
copy 16.a test16\Garden.OUT
md test17
copy 17. test17\Garden.INP
copy 17.a test17\Garden.OUT
md test18
copy 18. test18\Garden.INP
copy 18.a test18\Garden.OUT
md test19
copy 19. test19\Garden.INP
copy 19.a test19\Garden.OUT
md test20
copy 20. test20\Garden.INP
copy 20.a test20\Garden.OUT
md test21
copy 21. test21\Garden.INP
copy 21.a test21\Garden.OUT
md test22
copy 22. test22\Garden.INP
copy 22.a test22\Garden.OUT
md test23
copy 23. test23\Garden.INP
copy 23.a test23\Garden.OUT
md test24
copy 24. test24\Garden.INP
copy 24.a test24\Garden.OUT
md test25
copy 25. test25\Garden.INP
copy 25.a test25\Garden.OUT
md test26
copy 26. test26\Garden.INP
copy 26.a test26\Garden.OUT
md test27
copy 27. test27\Garden.INP
copy 27.a test27\Garden.OUT
md test28
copy 28. test28\Garden.INP
copy 28.a test28\Garden.OUT
md test29
copy 29. test29\Garden.INP
copy 29.a test29\Garden.OUT
md test30
copy 30. test30\Garden.INP
copy 30.a test30\Garden.OUT
md test31
copy 31. test31\Garden.INP
copy 31.a test31\Garden.OUT
md test32
copy 32. test32\Garden.INP
copy 32.a test32\Garden.OUT
md test33
copy 33. test33\Garden.INP
copy 33.a test33\Garden.OUT
md test34
copy 34. test34\Garden.INP
copy 34.a test34\Garden.OUT
md test35
copy 35. test35\Garden.INP
copy 35.a test35\Garden.OUT
md test36
copy 36. test36\Garden.INP
copy 36.a test36\Garden.OUT
md test37
copy 37. test37\Garden.INP
copy 37.a test37\Garden.OUT
md test38
copy 38. test38\Garden.INP
copy 38.a test38\Garden.OUT
md test39
copy 39. test39\Garden.INP
copy 39.a test39\Garden.OUT
md test40
copy 40. test40\Garden.INP
copy 40.a test40\Garden.OUT
md test41
copy 41. test41\Garden.INP
copy 41.a test41\Garden.OUT
md test42
copy 42. test42\Garden.INP
copy 42.a test42\Garden.OUT
