ren roz1ocen.in differ.in.31
ren roz1ocen.out differ.expect.31
ren roz2ocen.in differ.in.32
ren roz2ocen.out differ.expect.32
ren roz3ocen.in differ.in.33
ren roz3ocen.out differ.expect.33
ren roz4ocen.in differ.in.34
ren roz4ocen.out differ.expect.34
ren roz5ocen.in differ.in.35
ren roz5ocen.out differ.expect.35
